name: petualangan_rupi
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  audioplayers: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/si_rupi_waving.png
    - assets/images/judul_game.png
    - assets/images/main_menu_bg.png
    - assets/images/splash_screen/background.png
    - assets/images/pencapaian/background.png
    - assets/images/pencapaian/teks.png
    - assets/images/pencapaian/dunia_cinta.png
    - assets/images/pencapaian/dunia_bangga.png
    - assets/images/pencapaian/dunia_paham.png
    - assets/images/konfirmasi_keluar/si_rupi_sad.png
    - assets/images/konfirmasi_keluar/teks.png
    - assets/images/konfirmasi_keluar/background.png
    - assets/images/pemilihan-misi/misi_bg.png
    - assets/images/pemilihan-misi/teks-pilih-dunia.png
    - assets/images/pemilihan-misi/dunia_cinta.png
    - assets/images/pemilihan-misi/dunia_bangga.png
    - assets/images/pemilihan-misi/dunia_paham.png
    - assets/images/pengaturan/background-pengaturan.png
    - assets/images/pengaturan/teks-pengaturan.png
    - assets/images/pengaturan/si_rupi_waving.png
    - assets/images/benar_salah/benar.png
    - assets/images/benar_salah/salah.png
    - assets/images/game/dunia-cinta/karakter-rupi.png
    - assets/images/game/dunia-cinta/asli-1.png
    - assets/images/game/dunia-cinta/asli-2.png
    - assets/images/game/dunia-cinta/asli-3.png
    - assets/images/game/dunia-cinta/asli-4.png
    - assets/images/game/dunia-cinta/asli-5.png
    - assets/images/game/dunia-cinta/asli-6.png
    - assets/images/game/dunia-cinta/asli-7.png
    - assets/images/game/dunia-cinta/palsu-1.png
    - assets/images/game/dunia-cinta/palsu-2.png
    - assets/images/game/dunia-cinta/palsu-3.png
    - assets/images/game/dunia-cinta/palsu-4.png
    - assets/images/game/dunia-cinta/palsu-5.png
    - assets/images/pencapaianduniacinta/background.png
    - assets/images/pencapaianduniabangga/background.png
    - assets/images/pencapaianduniapaham/background.png
    - assets/images/pencapaianduniacinta/teks-dunia-cinta.png
    - assets/images/pencapaianduniabangga/teks-dunia-bangga.png
    - assets/images/pencapaianduniapaham/teks-dunia-paham.png
    - assets/images/pencapaianduniacinta/lencana_cinta.png
    - assets/images/pencapaianduniabangga/lencana_bangga.png
    - assets/images/pencapaianduniapaham/lencana_paham.png
    - assets/images/game/dunia-bangga/asli-1.png
    - assets/images/game/dunia-bangga/asli-2.png
    - assets/images/game/dunia-bangga/asli-3.jpeg
    - assets/images/game/dunia-bangga/asli-4.jpeg
    - assets/images/game/dunia-bangga/asli-5.jpeg
    - assets/images/game/dunia-bangga/asli-6.jpeg
    - assets/images/game/dunia-bangga/asli-7.png
    - assets/images/game/dunia-bangga/background.png
    - assets/images/game/dunia-bangga/si_rupi_waving.png
    - assets/images/game/dunia-paham/uang_1000.jpeg
    - assets/images/game/dunia-paham/uang_2000.png
    - assets/images/game/dunia-paham/uang_5000.png
    - assets/images/game/dunia-paham/uang_10000.png
    - assets/images/game/dunia-paham/uang_20000.jpeg
    - assets/images/game/dunia-paham/uang_50000.jpeg
    - assets/images/game/dunia-paham/uang_100000.jpeg
    - assets/images/game/dunia-paham/coin_mascot.png
    - assets/images/game/dunia-paham/background.png
    - assets/audio/background_music.mp3
    - assets/audio/click_sound.mp3

  fonts:
    - family: Fredoka
      fonts:
        - asset: assets/fonts/fredoka.ttf
